config/routes.rb
Rails.application.routes.draw do
  
  match "calendar/data", :to => "calendar#data", :as => "data", :via => "get"
  match "calendar/db_action", :to => "calendar#db_action", :as => "db_action", :via => "post"
  resources :calendar
  resources :properties
  resources :projects do
    resources :settings
    end
 


  
  root :to => 'projects#index'
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
  def data
    events = Event.all
 
    render :json => events.map {|event| {
               :id => event.id,
               :start_date => event.start_date.to_formatted_s(:db),
               :end_date => event.end_date.to_formatted_s(:db),
               :text => event.text
           }}
  end
  
  def db_action
    mode = params["!nativeeditor_status"]
    id = params["id"]
    start_date = params["start_date"]
    end_date = params["end_date"]
    text = params["text"]
 
    case mode
      when "inserted"
        event = Event.create :start_date => start_date, :end_date => end_date, :text => text
        tid = event.id
 
      when "deleted"
        Event.find(id).destroy
        tid = id
 
      when "updated"
        event = Event.find(id)
        event.start_date = start_date
        event.end_date = end_date
        event.text = text
        event.save
        tid = id
    end
 
    render :json => {
               :type => mode,
               :sid => id,
               :tid => tid,
           }
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendar/index.html.erb
<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
    <div class="dhx_cal_navline">
      <div class="dhx_cal_prev_button">&nbsp;</div>
      <div class="dhx_cal_next_button">&nbsp;</div>
      <div class="dhx_cal_today_button"></div>
      <div class="dhx_cal_date"></div>
      <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
      <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
      <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
    </div>
    <div class="dhx_cal_header">
    </div>
    <div class="dhx_cal_data">
    </div>
   </div>
   
   <script>
       
	    scheduler.config.mark_now = true;
        scheduler.config.details_on_dblclick=true;
		scheduler.config.details_on_create=true;
		
		scheduler.attachEvent("onEventSave",function(id,ev){
			if (!ev.text) {
				dhtmlx.alert("Text must not be empty");
				return false;
			}
			if (ev.text.length<5) {
				dhtmlx.alert("Text too small");
				return false;
			}
			return true;
		});
       scheduler.config.xml_date="%Y-%m-%d %H:%i";
       
       scheduler.init("scheduler_here");
       scheduler.load("<%= data_path %>", "json");
       var dp = new dataProcessor("<%= db_action_path %>");
       dp.init(scheduler);
       dp.setTransactionMode("POST", false);
   </script>