config/routes.rb
Rails.application.routes.draw do
  
  match "calendar/data", :to => "calendar#data", :as => "data", :via => "get"
  match "calendar/db_action", :to => "calendar#db_action", :as => "db_action", :via => "post"
  resources :calendar
  resources :properties
  resources :projects do
    resources :settings
    end
 


  
  root :to => 'projects#index'
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :project
    validates :name, :presence => true
    has_many :location_associations
    has_many :properties, through: :location_associations
    


end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :get_project
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = @project.settings.to_a
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = @project.settings.build
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = @project.settings.build(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to project_settings_path(@project), notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to project_settings_path(@project), notice: 'Setting was successfully updated.' }
        #format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to project_settings_path(@project), notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def get_project
      @project = Project.find(params[:project_id])
    end


    def set_setting
      @setting = @project.settings.find(params[:id])
    end

    

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:name, :placement, :description, :s_filming_date, :e_filming_date, :project_id, property_ids:[])
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: [@project, setting], local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :placement %>
    <%= form.text_field :placement %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :s_filming_date %>
    <%= form.date_select :s_filming_date %>
  </div>

  <div class="field">
    <%= form.label :e_filming_date %>
    <%= form.date_select :e_filming_date %>
  </div>


  <div class="field">
  <%= hidden_field_tag "setting[property_ids][]", nil %>
  <% Property.all.each do |property| %>
    <%= check_box_tag "setting[property_ids][]", property.id, @setting.property_ids.include?(property.id), id: dom_id(property) %>
    <%= label_tag dom_id(property), property.name %><br>
  <% end %>

</div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', project_setting_path %> |
<%= link_to 'Back', project_settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Placement</th>
      <th>Description</th>
      <th>S filming date</th>
      <th>E filming date</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><%= setting.placement %></td>
        <td><%= setting.description %></td>
        <td><%= setting.s_filming_date %></td>
        <td><%= setting.e_filming_date %></td>
        <td><%= setting.project.name %></td>
        <td><%= link_to 'Show', project_setting_path(@project, setting) %></td>
        <td><%= link_to 'Edit', edit_project_setting_path(@project, setting) %></td>
        <td><%= link_to 'Destroy', project_setting_path(@project, setting), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_project_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', project_settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Placement:</strong>
  <%= @setting.placement %>
</p>

<p>
  <strong>Description:</strong>
  <%= @setting.description %>
</p>

<p>
  <strong>S filming date:</strong>
  <%= @setting.s_filming_date %>
</p>

<p>
  <strong>E filming date:</strong>
  <%= @setting.e_filming_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @setting.project.name %>
</p>

<p>
  <strong>Properties:</strong>
  <% @setting.properties.each do |property| %>
    <li><%= property.name %></li>
  <% end %>
</p>

<%= link_to 'Edit', edit_project_setting_path %> |
<%= link_to 'Back', project_settings_path %>